version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: teste-simples
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
    volumes:
      - ./:/var/www
    working_dir: /var/www
