version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cms-api
    container_name: cms-api-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=Soffia-database
      - DB_USERNAME=postgres
      - DB_PASSWORD=Erikbarbosa12
      - JWT_SECRET=nP6QlImMGm1qxKchPY2IKOIwkMwtNTKzSU81he9dFil9yX0autVvmboKTzmr28HY
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - cms-api-network

  nginx:
    image: nginx:alpine
    container_name: cms-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cms-api-network

  db:
    image: postgres:15
    container_name: cms-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: Soffia-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Erikbarbosa12
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cms-api-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: cms-api-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - cms-api-network

networks:
  cms-api-network:
    driver: bridge

volumes:
  db_data:
    driver: local



