version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.railway
    image: teste-back-soffia-app-railway
    container_name: teste-railway
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=containers-us-west-123.railway.app
      - DB_PORT=23644
      - DB_DATABASE=railway
      - DB_USERNAME=postgres
      - DB_PASSWORD=YbISVzRIeLMsfuvNDLUHkyAYRIbZWOdS
      - JWT_SECRET=4uWNPG9DrFCjSBIjgZ1HoEgeZNp6I2dquOdZbajYznTwcLRlRGRXhCmH050ZTZ95
      - CACHE_DRIVER=array
      - SESSION_DRIVER=array
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    networks:
      - railway-network

networks:
  railway-network:
    driver: bridge
