[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "if [ ! -f .env ]; then cp .env.example .env 2>/dev/null || echo 'APP_NAME=\"CMS API\"' > .env; fi",
  "php artisan key:generate --force",
  "php artisan jwt:secret --force"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"
