[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "cp .env.example .env",
  "php artisan key:generate --force",
  "php artisan jwt:secret --force"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"
